# Generated by BoostInstall.cmake for boost_wserialization-1.89.0

if(Boost_VERBOSE OR Boost_DEBUG)
  message(STATUS "Found boost_wserialization ${boost_wserialization_VERSION} at ${boost_wserialization_DIR}")
endif()

include(CMakeFindDependencyMacro)


find_dependency(boost_serialization 1.89.0 EXACT HINTS "${CMAKE_CURRENT_LIST_DIR}/..")

include("${CMAKE_CURRENT_LIST_DIR}/boost_wserialization-targets.cmake")
