# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.30)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS octomath octomath-static octomap octomap-static)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Release"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomath.1.9.8.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/liboctomath.1.9.dylib"
  )

# Import target "octomath-static" for configuration "Release"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomath.a"
  )

# Import target "octomap" for configuration "Release"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomap.1.9.8.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/liboctomap.1.9.dylib"
  )

# Import target "octomap-static" for configuration "Release"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.30)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS octomath octomath-static octomap octomap-static)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Release"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomath.1.9.8.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/liboctomath.1.9.dylib"
  )

# Import target "octomath-static" for configuration "Release"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomath.a"
  )

# Import target "octomap" for configuration "Release"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomap.1.9.8.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/liboctomap.1.9.dylib"
  )

# Import target "octomap-static" for configuration "Release"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.30)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS octomath octomath-static octomap octomap-static)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "RelWithDebInfo"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomath.1.9.8.dylib"
  IMPORTED_SONAME_RELWITHDEBINFO "@rpath/liboctomath.1.9.dylib"
  )

# Import target "octomath-static" for configuration "RelWithDebInfo"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomath.a"
  )

# Import target "octomap" for configuration "RelWithDebInfo"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomap.1.9.8.dylib"
  IMPORTED_SONAME_RELWITHDEBINFO "@rpath/liboctomap.1.9.dylib"
  )

# Import target "octomap-static" for configuration "RelWithDebInfo"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.30)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS octomath octomath-static octomap octomap-static)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Release"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomath.1.9.8.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/liboctomath.1.9.dylib"
  )

# Import target "octomath-static" for configuration "Release"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomath.a"
  )

# Import target "octomap" for configuration "Release"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomap.1.9.8.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/liboctomap.1.9.dylib"
  )

# Import target "octomap-static" for configuration "Release"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/octomap/lib/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
