# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.30)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS dynamicedt3d dynamicedt3d-static)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target dynamicedt3d
add_library(dynamicedt3d SHARED IMPORTED)

set_target_properties(dynamicedt3d PROPERTIES
  INTERFACE_LINK_LIBRARIES "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/lib/liboctomap.dylib;/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/lib/liboctomath.dylib"
)

# Create imported target dynamicedt3d-static
add_library(dynamicedt3d-static STATIC IMPORTED)

set_target_properties(dynamicedt3d-static PROPERTIES
  INTERFACE_LINK_LIBRARIES "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/lib/liboctomap.dylib;/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/lib/liboctomath.dylib"
)

# Import target "dynamicedt3d" for configuration "Release"
set_property(TARGET dynamicedt3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dynamicedt3d PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/lib/libdynamicedt3d.1.9.8.dylib"
  IMPORTED_SONAME_RELEASE "@rpath/libdynamicedt3d.1.9.dylib"
  )

# Import target "dynamicedt3d-static" for configuration "Release"
set_property(TARGET dynamicedt3d-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(dynamicedt3d-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/dhruvpatel29/humble-ros2/src/moveit/octomap-release/lib/libdynamicedt3d.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
